# Generated by Django 2.2.6 on 2021-05-19 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0005_auto_20191104_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='connections',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('non-binary', 'Non-Binary'), ('choose-not-to-self-identify', 'Choose Not To Self Identify')], max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='info',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
