# Generated by Django 2.2.6 on 2021-05-19 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0006_auto_20210519_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='location',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
